# Starter pipeline
- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: 'https://10.26.38.144'
    conjuraccount: 'myConjurAccount'
    conjurusername: 'admin'
    conjurapikey: '28zf3k11hvm0gm1sycjvq3zqyap7wdjsd13bc0jb358zkr72xpsbv5'
    ignoreSsl: true

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SnykSecurityScan@0
  inputs:
    serviceConnectionEndpoint: 'prachi_con'
    testType: 'app'
    monitorOnBuild: true
    failOnIssues: true